return {
  { "folke/tokyonight.nvim", enabled = false },
  { "catppuccin", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "goolord/alpha-nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "dstein64/vim-startuptime", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "Exafunction/codeium.vim", enabled = false },
  -- { "nvim-lualine/lualine.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "axkirillov/hbac.nvim", enabled = false },
  -- { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
}
